### ISSUE TITLE
Index Error

### ISSUE THREAD

**Issue by echylon** [PaulSec/API-dnsdumpster.com#35]
Any updates on the following issue?

res['dns_records']['dns'] = self.retrieve_results(tables[0])
                                                     
IndexError: list index out of range

**Comment by decidedlygray** [comment]
Does it happen for every domain you're trying?

**Comment by echylon** [comment]
Yup, was working fine for almost two days. No changes and just stopped working.

**Comment by decidedlygray** [comment]
It is working for me on the `uber.com` example included in the `API_example.py`.

Some domains are returning an empty page on the real https://dnsdumpster.com which results in me seeing the error you have. For example, modifying the `API_example.py` to point to `example.com` I see this:

```bash
──(root💀kali)-[/opt/API-dnsdumpster.com]
└─# python API_example.py
Testing... : example.com
[verbose] Retrieved token: w1Gyf8xxxweX8
Traceback (most recent call last):
  File "API_example.py", line 10, in <module>
    res = DNSDumpsterAPI(True).search(domain)
  File "/opt/API-dnsdumpster.com/dnsdumpster/DNSDumpsterAPI.py", line 98, in search
    res['dns_records']['dns'] = self.retrieve_results(tables[0])
IndexError: list index out of range
```

I did confirm `example.com` with https://hackertarget.com/dns-lookup/ where I do see there are supposed to be DNS records returned. Since in this case dnsdumpster.com itself seems to be the source of the problem, there isn't much this tool can do except maybe implement error checking for empty results.

I'd give the above a try with whatever domain you're trying. If that doesn't work, if you could provide a domain you're seeing it on and a stack trace that would be helpful for debugging.

**Comment by echylon** [comment]
Uber.com is one that I have tried as well.
